// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "PoleZeroEditorGUI.hxx"
#include "VERSION.hxx"

inline void PoleZeroEditorGUI::cb_mPolesList_i(PoleZeroList*, void*) {
  Edited(kPole);
}
void PoleZeroEditorGUI::cb_mPolesList(PoleZeroList* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_mPolesList_i(o,v);
}

inline void PoleZeroEditorGUI::cb_mZerosList_i(PoleZeroList*, void*) {
  Edited(kZero);
}
void PoleZeroEditorGUI::cb_mZerosList(PoleZeroList* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_mZerosList_i(o,v);
}

inline void PoleZeroEditorGUI::cb_Quit_i(Fl_Menu_* o, void*) {
  delete o->window();
}
void PoleZeroEditorGUI::cb_Quit(Fl_Menu_* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->user_data()))->cb_Quit_i(o,v);
}

inline void PoleZeroEditorGUI::cb_Cut_i(Fl_Menu_*, void*) {
  RemoveSelected();
}
void PoleZeroEditorGUI::cb_Cut(Fl_Menu_* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->user_data()))->cb_Cut_i(o,v);
}

inline void PoleZeroEditorGUI::cb_Delete_i(Fl_Menu_*, void*) {
  RemoveSelected();
}
void PoleZeroEditorGUI::cb_Delete(Fl_Menu_* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->user_data()))->cb_Delete_i(o,v);
}

inline void PoleZeroEditorGUI::cb_Select_i(Fl_Menu_*, void*) {
  SelectAll();
}
void PoleZeroEditorGUI::cb_Select(Fl_Menu_* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->user_data()))->cb_Select_i(o,v);
}

inline void PoleZeroEditorGUI::cb_About_i(Fl_Menu_*, void*) {
  About();
}
void PoleZeroEditorGUI::cb_About(Fl_Menu_* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item PoleZeroEditorGUI::menu_[] = {
 {"File", 0,  0, 0, 64, 0, 0, 14, 0},
 {"New", 0,  0, 0, 1, 0, 0, 14, 0},
 {"Open", 0x4006f,  0, 0, 1, 0, 0, 14, 0},
 {"Save", 0x40073,  0, 0, 1, 0, 0, 14, 0},
 {"Save as ...", 0,  0, 0, 1, 0, 0, 14, 0},
 {"Close", 0x40077,  0, 0, 1, 0, 0, 14, 0},
 {"Quit", 0x40071,  (Fl_Callback*)PoleZeroEditorGUI::cb_Quit, 0, 0, 0, 0, 14, 0},
 {0},
 {"Edit", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Cut", 0x40078,  (Fl_Callback*)PoleZeroEditorGUI::cb_Cut, 0, 0, 0, 0, 14, 0},
 {"Copy", 0x40063,  0, 0, 1, 0, 0, 14, 0},
 {"Paste", 0x40076,  0, 0, 1, 0, 0, 14, 0},
 {"Delete", 0xffff,  (Fl_Callback*)PoleZeroEditorGUI::cb_Delete, 0, 0, 0, 0, 14, 0},
 {"Select all", 0x40061,  (Fl_Callback*)PoleZeroEditorGUI::cb_Select, 0, 0, 0, 0, 14, 0},
 {0},
 {"Help", 0,  0, 0, 64, 0, 0, 14, 0},
 {"About ...", 0,  (Fl_Callback*)PoleZeroEditorGUI::cb_About, 0, 0, 0, 0, 14, 0},
 {0},
 {0}
};

inline void PoleZeroEditorGUI::cb_mAddPoleButton_i(ToolTipButton*, char*) {
  SetAddMode(kAddModePole);
}
void PoleZeroEditorGUI::cb_mAddPoleButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mAddPoleButton_i(o,v);
}

#include <FL/Fl_Bitmap.H>
static unsigned char bits_pole[] =
"\0\0\0\0\f0\34""88\34p\16\340\7\300\3\300\3\340\7p\16""8\34\34""8\f0\0\0\0\0";
static Fl_Bitmap bitmap_pole(bits_pole, 16, 16);

inline void PoleZeroEditorGUI::cb_mAddZeroButton_i(ToolTipButton*, char*) {
  SetAddMode(kAddModeZero);
}
void PoleZeroEditorGUI::cb_mAddZeroButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mAddZeroButton_i(o,v);
}

static unsigned char bits_zero[] =
"\0\0\0\0\300\3\360\17""8\34\30\30\f0\f0\f0\f0\30\30""8\34\360\17\300\3\0\0\0\
\0";
static Fl_Bitmap bitmap_zero(bits_zero, 16, 16);

inline void PoleZeroEditorGUI::cb_mSelectButton_i(ToolTipButton*, char*) {
  SetMoveMode(kMoveModeSelect);
}
void PoleZeroEditorGUI::cb_mSelectButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mSelectButton_i(o,v);
}

static unsigned char bits_arrow[] =
"\0\0\20\0""0\0p\0\360\0\360\1\360\3\360\7\360\17\360\1\260\1\20\3\0\3\0\6\0\
\6\0\0";
static Fl_Bitmap bitmap_arrow(bits_arrow, 16, 16);

inline void PoleZeroEditorGUI::cb_mMoveXYButton_i(ToolTipButton*, char*) {
  SetMoveMode(kMoveModeXY);
}
void PoleZeroEditorGUI::cb_mMoveXYButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mMoveXYButton_i(o,v);
}

static unsigned char bits_movexy[] =
"\200\1\300\3\340\7\0\0\200\1\204!\206""a\367\357\367\357\206""a\204!\200\1\0\
\0\340\7\300\3\200\1";
static Fl_Bitmap bitmap_movexy(bits_movexy, 16, 16);

inline void PoleZeroEditorGUI::cb_mMoveAngButton_i(ToolTipButton*, char*) {
  SetMoveMode(kMoveModeAng);
}
void PoleZeroEditorGUI::cb_mMoveAngButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mMoveAngButton_i(o,v);
}

static unsigned char bits_moveang[] =
"\3\0\3\0\3 \3\20\3\b\3\0\3>\3>\203\6""C6#6\23`\13`\7\0\377\377\377\377";
static Fl_Bitmap bitmap_moveang(bits_moveang, 16, 16);

inline void PoleZeroEditorGUI::cb_mMoveMagButton_i(ToolTipButton*, char*) {
  SetMoveMode(kMoveModeMag);
}
void PoleZeroEditorGUI::cb_mMoveMagButton(ToolTipButton* o, char* v) {
  ((PoleZeroEditorGUI*)(o->parent()->parent()->parent()->user_data()))->cb_mMoveMagButton_i(o,v);
}

static unsigned char bits_movemag[] =
"\3\0\3@\3 \3\37\3\37\3\30\3\33\263\33\263\1""3\0\363\1\363\1\13\0\7\0\377\
\377\377\377";
static Fl_Bitmap bitmap_movemag(bits_movemag, 16, 16);

static unsigned char bits_play[] =
"\0\0\0\0\f\0<\0\374\0\374\3\374\17\374?\374?\374\17\374\3\374\0<\0\f\0\0\0\0\
\0";
static Fl_Bitmap bitmap_play(bits_play, 16, 16);

static unsigned char bits_stop[] =
"\0\0\0\0\374?\374?\374?\374?\374?\374?\374?\374?\374?\374?\374?\374?\0\0\0\0";
static Fl_Bitmap bitmap_stop(bits_stop, 16, 16);

inline void PoleZeroEditorGUI::cb_OK_i(Fl_Return_Button* o, void*) {
  delete o->window();
}
void PoleZeroEditorGUI::cb_OK(Fl_Return_Button* o, void* v) {
  ((PoleZeroEditorGUI*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *image_polarbear[] = {
"100 70 17 1",
" \tc None",
".\tc #050505",
"+\tc #262626",
"@\tc #484848",
"#\tc #7F7F7F",
"$\tc #999999",
"%\tc #C3C3C3",
"&\tc #D0D0D0",
"*\tc #D8D8D8",
"=\tc #E0E0E0",
"-\tc #E6E6E6",
";\tc #EAEAEA",
">\tc #EEEEEE",
",\tc #F2F2F2",
"\'\tc #646464",
")\tc #B0B0B0",
"!\tc #FEFEFE",
"                                                                             \
                       ",
"                                                                             \
                       ",
"                                                                             \
                       ",
"                                                         %&====&&&&&%        \
                       ",
"                                                     &*,,!!!!!!!!!!!!>*%     \
                       ",
"                                                 %&=>!!!!!!!!!!!!!!!!!!,*%   \
                       ",
"                                               %=!!!!!!!!!!!!!!!!!!!!!!!!!=  \
                       ",
"                                      &***&==,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!,=\
%                      ",
"                                **;;;,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!=%                    ",
"                              &,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!,*%                  ",
"                           %*,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!=%                ",
"                        %=,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!,*               ",
"                      &;!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!*              ",
"                   &-,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!,%            ",
"                %-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!*           ",
"              &-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!;%         ",
"      )*&   );!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!;         ",
"     );!!*&=,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!&        ",
"     %,##,!!!!!!!!!!,\')!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!>        ",
"     )>@+=!!!!!!!!!!;.#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!;%      ",
"      *#\'!!!!!!!!!!!,+$!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!>      ",
"       -,!!!!!!!!!!!!*,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!&     ",
"       >!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!;     ",
"      &!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!,     ",
"      -!!!!!!!!!!!!!!!=-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!,     ",
"      ,!!!!!!!!!!!!!!!#\'!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!,     ",
"     #\',!!!!#@,!!!!!!!$@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!*    ",
"     #+;!!!!##!!!!!!!!)@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!%   ",
"      %!!!!!!!!!!!!!!!$@!!!!!)&!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!&   ",
"      =!!!!!!!!!!!!!!*+#!!!!>+$!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!=   ",
"      ,!!!!!!!!!!!!!!\'@;!!!!$.&!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!!=   ",
"     &!!!!!!!!!!!!!!=+)!!!!$.#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!>   ",
"     >!!!!!!!!!!!!!!,%,!!!!)),!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!>   ",
"    $$)=!!!!!!!!!!-&  %*,,!!!!!!!!!!!!!!!!!!!)%!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!>   ",
"    +..+&!!!!!!!!*        @@,!!!!!!!!!!!!!!!!#@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!>   ",
"    @...&!!!!!!,&         ++,!!!!!!!!!!!!!!!!%+,!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\
!!!!!!!!!!!!!!!!!!!>   ",
"     @.#>>$\',!>%          @+,!!!!!!!!!!!!!!!!%+,!!!!!!!!!!!!!!!!!!!!!!!!&;!!\
!!!!!!!!!!!!!!!!!!!!>   ",
"     $+++++$,*            \'\'!!!!!!!!!!!!!!!!!&+,!!!!!!!!!!!!!!!!!!!!!!!!@)!\
!!!!!!!!!!!!!!!!!!!!!>   ",
"      $$)$%=%             #\'!!!!!!!!!!!!!!!!!&+,!!!!!!!!!!!!!!!!!!!!!!!!@)!!\
!!!!!!!!!!!!!!!!!!!!&   ",
"                           #!!!!!!!!!!!!!!!!!$+,!!!!!!!!!!!!!!!!!!!!!!!,+)!!!\
!!!!!!!!!!!!!!!!!!,    ",
"                           #!!!!!!!!!!!!!!!!!@#!!!!!!!!!!!!!!!!!!!!!!!!,+)!!!\
!!!!!!!!!!!!!!!!!!=    ",
"                           @-!!!!!!!!!!!!!!!,+)!!!!!!!!!!!!!!!!!!!!!!!!,+)!!!\
!!!!!!!!!!!!!!!!!!&    ",
"                           +$!!!!!!!!!!!!!!!;+%!,;;;;>!!!!!!!!!!!!!!!!!>+)!!!\
!!!!!!!!!!!!!!!!!!&    ",
"                          \'.\'!!!!!!!!!!!!!!!=+&%       %=>!!!!!!!!!!!!!,+$!\
!!!!!!!!!!!!!!!!!!!!&    ",
"                         #+.\'!!!!!!!!!!!!!!!!*             &&=;!!!!!!!!!\'\'\
!!!!!!!!!!!!!!!!!!!!,     ",
"                         +..\'!!!!!!!!!!!!!!!!=                  &&======$+;!\
!!!!!!!!!!!!!!!!!!*     ",
"                        @...$!!!!!!!!!!!!!!!!%                          @.#,!\
!!!!!!!!!!!!!!!!;      ",
"                       #...+-!!!!!!!!!!!!!!!!                           #..$!\
!!!!!!!!!!!!!!!!%      ",
"                      $+...@!!!!!!!!!!!!!!!!;                            +.+,\
!!!!!!!!!!!!!!!!       ",
"                      @....\'!!!!!!!!!!!!!!!!;                            @..\
&!!!!!!!!!!!!!!!-       ",
"                     \'.....#!!!!!!!!!!!!!!!!*                            \'.\
.\'!!!!!!!!!!!!!!!-       ",
"                    #+.....)!!!!!!!!!!!!!!!!*                            #..+\
*!!!!!!!!!!!!!!=       ",
"                   $+.....+,!!!!!!!!!!!!!!!!%                             @..\
#!!!!!!!!!!!!!!&       ",
"                   \'......$!!!!!!!!!!!!!!!!!                              #.\
.@!!!!!!!!!!!!!!*       ",
"                   @.....@,!!!!!!!!!!!!!!!!,                               @.\
@!!!!!!!!!!!!!!%       ",
"                  #+.....%!!!!!!!!!!!!!!!!!;                               @.\
+,!!!!!!!!!!!!!        ",
"                  \'.....+;!!!!!!!!!!!!!!!!!*                               @\
..=!!!!!!!!!!!!!        ",
"                  #+....%!!!!!!!!!!!!!!!!!!&                               @.\
+,!!!!!!!!!!!!!        ",
"                   #\'@+)!!!!!!!!!!!!!!!!!!>                                @\
.$!!!!!!!!!!!!!!        ",
"                      %!!!!!!!!!!!!!!!!!!!*                               \'+\
$!!!!!!!!!!!!!!!        ",
"                      -!!!!!!!!!!!!!!!!!!!%                             $@+$!\
!!!!!!!!!!!!!!!        ",
"                      -!!!!!!!!!!!!!!!!!!=                              \'.$!\
!!!!!!!!!!!!!!!;        ",
"                      %=,!!!!!!!!!!!!!!!;%                              ++-!!\
!!!!!!!!!!!!!!*        ",
"                         &;!!!!!!!!=&&%                                 +@,!!\
!!!!!!!!!!!!!-         ",
"                             %&&&&                                       $&=;\
;;;>!!!!!!!!-          ",
"                                                                             \
    %&&&&&&%           ",
"                                                                             \
                       ",
"                                                                             \
                       ",
"                                                                             \
                       ",
"                                                                             \
                       "
};
static Fl_Pixmap pixmap_polarbear(image_polarbear);

PoleZeroEditorGUI::PoleZeroEditorGUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mWindow = new Fl_Double_Window(480, 475, "PolarBear - Complex Filter Design");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(3, 27, 480, 426);
      { Fl_Group* o = new Fl_Group(3, 27, 240, 240);
        { Fl_Group* o = new Fl_Group(3, 27, 237, 237);
          o->box(FL_THIN_DOWN_BOX);
          o->color(55);
          { PoleZeroPlane* o = mPoleZeroPlane = new PoleZeroPlane(4, 28, 235, 235);
            o->box(FL_FLAT_BOX);
            o->color(7);
            o->selection_color(1);
            Fl_Group::current()->resizable(o);
          }
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(243, 27, 240, 120);
        { Fl_Box* o = new Fl_Box(243, 27, 237, 18, "Amplitude Response");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Group* o = new Fl_Group(243, 45, 237, 99);
          o->box(FL_THIN_DOWN_BOX);
          o->color(55);
          { Fl_Amplitude_Response* o = mAmplitudeResponse = new Fl_Amplitude_Response(244, 46, 235, 97);
            o->box(FL_FLAT_BOX);
            o->color(7);
          }
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(243, 147, 240, 120);
        { Fl_Box* o = new Fl_Box(243, 147, 237, 18, "Phase Response");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Group* o = new Fl_Group(243, 165, 237, 99);
          o->box(FL_THIN_DOWN_BOX);
          o->color(7);
          { Fl_Phase_Response* o = mPhaseResponse = new Fl_Phase_Response(244, 166, 235, 97);
            o->box(FL_FLAT_BOX);
            o->color(7);
          }
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(3, 267, 240, 96);
        { Fl_Box* o = new Fl_Box(3, 267, 237, 18, "Poles");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Scroll* o = new Fl_Scroll(3, 285, 237, 75);
          o->type(6);
          o->box(FL_THIN_DOWN_BOX);
          o->color(7);
          { PoleZeroList* o = mPolesList = new PoleZeroList(4, 286, 219, 73);
            o->color(7);
            o->selection_color(1);
            o->callback((Fl_Callback*)cb_mPolesList);
          }
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(242, 267, 241, 96);
        { Fl_Box* o = new Fl_Box(243, 267, 237, 18, "Zeros");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Scroll* o = new Fl_Scroll(243, 285, 237, 75);
          o->type(6);
          o->box(FL_THIN_DOWN_BOX);
          o->color(7);
          { PoleZeroList* o = mZerosList = new PoleZeroList(244, 286, 219, 73);
            o->color(7);
            o->selection_color(1);
            o->callback((Fl_Callback*)cb_mZerosList);
          }
          o->end();
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(3, 363, 240, 90);
        { Fl_Box* o = new Fl_Box(3, 363, 237, 18, "b Coefficients");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Browser* o = mBCoefsBrowser = new Fl_Browser(3, 381, 237, 69);
          o->box(FL_THIN_DOWN_BOX);
          o->selection_color(49);
          o->textfont(4);
          Fl_Group::current()->resizable(o);
          o->has_scrollbar(Fl_Browser::VERTICAL_ALWAYS);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(243, 363, 240, 90);
        { Fl_Box* o = new Fl_Box(243, 363, 237, 18, "a Coefficients");
          o->box(FL_THIN_DOWN_BOX);
          o->color(0);
          o->selection_color(0);
          o->labelsize(12);
          o->labelcolor(7);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Browser* o = mACoefsBrowser = new Fl_Browser(243, 381, 237, 69);
          o->box(FL_THIN_DOWN_BOX);
          o->selection_color(49);
          o->textfont(4);
          Fl_Group::current()->resizable(o);
          o->has_scrollbar(Fl_Browser::VERTICAL_ALWAYS);
        }
        o->end();
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = new Fl_Group(0, -3, 483, 27);
      { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, -2, 276, 26);
        o->box(FL_THIN_UP_BOX);
        o->selection_color(46);
        Fl_Group::current()->resizable(o);
        o->menu(menu_);
      }
      { Fl_Box* o = new Fl_Box(276, 0, 3, 24);
        o->box(FL_THIN_UP_BOX);
      }
      { Fl_Group* o = new Fl_Group(279, 0, 48, 24);
        { ToolTipButton* o = mAddPoleButton = new ToolTipButton(279, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_pole.label(o);
          o->callback((Fl_Callback*)cb_mAddPoleButton, (void*)("Doubleclick to add pole, ctrl+doubleclick to add conjugate pair"));
        }
        { ToolTipButton* o = mAddZeroButton = new ToolTipButton(303, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_zero.label(o);
          o->callback((Fl_Callback*)cb_mAddZeroButton, (void*)("Doubleclick to add zero, ctrl+doubleclick to add conjugate pair"));
        }
        o->end();
      }
      { Fl_Box* o = new Fl_Box(327, 0, 3, 24);
        o->box(FL_THIN_UP_BOX);
      }
      { Fl_Group* o = new Fl_Group(330, 0, 99, 24);
        { ToolTipButton* o = mSelectButton = new ToolTipButton(330, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_arrow.label(o);
          o->callback((Fl_Callback*)cb_mSelectButton, (void*)("Click to select, shift+click to add, ctrl+click to toggle"));
        }
        { Fl_Box* o = new Fl_Box(354, 0, 3, 24);
          o->box(FL_THIN_UP_BOX);
        }
        { ToolTipButton* o = mMoveXYButton = new ToolTipButton(357, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_movexy.label(o);
          o->callback((Fl_Callback*)cb_mMoveXYButton, (void*)("Move in both directions"));
        }
        { ToolTipButton* o = mMoveAngButton = new ToolTipButton(381, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_moveang.label(o);
          o->callback((Fl_Callback*)cb_mMoveAngButton, (void*)("Modify angle"));
        }
        { ToolTipButton* o = mMoveMagButton = new ToolTipButton(405, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_movemag.label(o);
          o->callback((Fl_Callback*)cb_mMoveMagButton, (void*)("Modify magnitude"));
        }
        o->end();
      }
      { Fl_Box* o = new Fl_Box(429, 0, 3, 24);
        o->box(FL_THIN_UP_BOX);
      }
      { Fl_Group* o = new Fl_Group(432, 0, 48, 24);
        { Fl_Button* o = mPlayButton = new Fl_Button(432, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_play.label(o);
          o->deactivate();
        }
        { Fl_Button* o = mStopButton = new Fl_Button(456, 0, 24, 24);
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          bitmap_stop.label(o);
          o->deactivate();
        }
        o->end();
      }
      { Fl_Box* o = new Fl_Box(480, 0, 3, 24);
        o->box(FL_THIN_UP_BOX);
      }
      o->end();
    }
    { Fl_Box* o = ToolTipButton::tooltipBox = new Fl_Box(279, 25, 201, 41);
      o->box(FL_BORDER_BOX);
      o->color(215);
      o->labelsize(10);
      o->align(133|FL_ALIGN_INSIDE);
      o->hide();
    }
    { Fl_Slider* o = mGainSlider = new Fl_Slider(3, 453, 237, 18);
      o->type(1);
      o->box(FL_THIN_DOWN_BOX);
    }
    o->end();
  }
}

void PoleZeroEditorGUI::About(void) {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(235, 235);
    w = o;
    o->box(FL_UP_BOX);
    o->user_data((void*)(this));
    new Fl_Box(0, 18, 234, 22, "PolarBear");
    { Fl_Box* o = new Fl_Box(0, 83, 234, 22, "maarten@@resorama.com");
      o->labelfont(4);
      o->labelcolor(4);
    }
    { Fl_Return_Button* o = new Fl_Return_Button(75, 204, 84, 21, "OK");
      o->box(FL_THIN_UP_BOX);
      o->callback((Fl_Callback*)cb_OK);
    }
    { Fl_Box* o = new Fl_Box(-3, 65, 237, 20, "VERSION");
      o->label(version);
    }
    new Fl_Box(0, 42, 234, 23, "Complex Filter Design");
    { Fl_Box* o = new Fl_Box(15, 105, 205, 90);
      pixmap_polarbear.label(o);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    o->show();
    o->set_non_modal();
    o->clear_border();
    o->end();
  }
}

